global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'budget-service'
    metrics_path: '/actuator/prometheus'
    dns_sd_configs:
      - names:
          - 'budget-service'
        type: 'A'
        port: 8081
    scrape_interval: 5s

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['budget-gateway:8080']
    scrape_interval: 5s
