server:
  port: ${EUREKA_SERVER_PORT:8761}

spring:
  application:
    name: eureka-server
  threads:
    virtual:
      enabled: ${VIRTUAL_THREADS_ENABLED:true}
  security:
    user:
      name: ${EUREKA_USER:eureka}
      password: ${EUREKA_PASSWORD:eureka123}

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_EXPOSE_ENDPOINTS:health,info,metrics,prometheus}
  endpoint:
    health:
      show-details: ${ACTUATOR_HEALTH_SHOW_DETAILS:always}

